// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quizate.API.Data;

#nullable disable

namespace Quizate.Data.Migrations
{
    [DbContext(typeof(QuizateDbContext))]
    [Migration("20260221141915_AddQuestionAndOption")]
    partial class AddQuestionAndOption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quizate.Data.Models.MultipleChoiceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_multiple_choice_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_multiple_choice_options_question_id");

                    b.ToTable("multiple_choice_options", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "London"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Rome"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Berlin"
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_multiple_choice_questions");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_multiple_choice_questions_quiz_id");

                    b.ToTable("multiple_choice_questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            QuizId = new Guid("d1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Text = "What is the capital of France?"
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<Guid>("QuizTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_type_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_quizzes_creator_id");

                    b.HasIndex("QuizTypeId")
                        .HasDatabaseName("ix_quizzes_quiz_type_id");

                    b.ToTable("quizzes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc).AddTicks(1654),
                            CreatorId = new Guid("655a37fa-b9e1-4cad-a684-383ac587e906"),
                            Description = "This is a sample quiz.",
                            IsPublic = true,
                            QuizTypeId = new Guid("12345678-1234-1234-1234-123456789012"),
                            Title = "Sample Quiz",
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc).AddTicks(1654)
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.QuizType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quiz_types");

                    b.ToTable("quiz_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12345678-1234-1234-1234-123456789012"),
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc).AddTicks(1654),
                            DisplayName = "Standard",
                            Name = "standard",
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc).AddTicks(1654)
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("655a37fa-b9e1-4cad-a684-383ac587e906"),
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc).AddTicks(1654),
                            Email = "demo_user@example.com",
                            HashedPassword = "hashed_password_placeholder",
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc).AddTicks(1654),
                            Username = "demo_user"
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.MultipleChoiceOption", b =>
                {
                    b.HasOne("Quizate.Data.Models.MultipleChoiceQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_multiple_choice_options_multiple_choice_questions_question_");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quizate.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasOne("Quizate.Data.Models.Quiz", "Quiz")
                        .WithMany("MultipleChoiceQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_multiple_choice_questions_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quizate.Data.Models.Quiz", b =>
                {
                    b.HasOne("Quizate.Data.Models.User", "Creator")
                        .WithMany("Quizzes")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("fk_quizzes_users_creator_id");

                    b.HasOne("Quizate.Data.Models.QuizType", "QuizType")
                        .WithMany("Quizzes")
                        .HasForeignKey("QuizTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizzes_quiz_types_quiz_type_id");

                    b.Navigation("Creator");

                    b.Navigation("QuizType");
                });

            modelBuilder.Entity("Quizate.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Quizate.Data.Models.Quiz", b =>
                {
                    b.Navigation("MultipleChoiceQuestions");
                });

            modelBuilder.Entity("Quizate.Data.Models.QuizType", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("Quizate.Data.Models.User", b =>
                {
                    b.Navigation("Quizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
