// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quizate.API.Data;

#nullable disable

namespace Quizate.Data.Migrations
{
    [DbContext(typeof(QuizateDbContext))]
    [Migration("20260307084348_DatabaseRedesignAndMigrationReset")]
    partial class DatabaseRedesignAndMigrationReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizQuizTopic", b =>
                {
                    b.Property<Guid>("QuizzesId")
                        .HasColumnType("uuid")
                        .HasColumnName("quizzes_id");

                    b.Property<string>("TopicsName")
                        .HasColumnType("character varying(25)")
                        .HasColumnName("topics_name");

                    b.HasKey("QuizzesId", "TopicsName")
                        .HasName("pk_quiz_quiz_topic");

                    b.HasIndex("TopicsName")
                        .HasDatabaseName("ix_quiz_quiz_topic_topics_name");

                    b.ToTable("quiz_quiz_topic", (string)null);
                });

            modelBuilder.Entity("Quizate.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("QuestionTypeName")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_type_name");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.HasKey("Id")
                        .HasName("pk_question");

                    b.HasIndex("QuestionTypeName")
                        .HasDatabaseName("ix_question_question_type_name");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_question_quiz_id");

                    b.ToTable("question", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Payload = "{\"Title\":\"What's the capital of Turkey?\",\"Options\":[{\"Text\":\"Istanbul\",\"IsCorrect\":false},{\"Text\":\"Ankara\",\"IsCorrect\":true},{\"Text\":\"Izmir\",\"IsCorrect\":false},{\"Text\":\"Bursa\",\"IsCorrect\":false}]}",
                            QuestionTypeName = "multiple_choice",
                            QuizId = new Guid("d1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.QuestionType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_question_types");

                    b.ToTable("question_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_quiz_types_name_not_empty", "char_length(trim(name)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Name = "multiple_choice",
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_quizzes_creator_id");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_quizzes_language_code");

                    b.ToTable("quizzes", null, t =>
                        {
                            t.HasCheckConstraint("ck_quizzes_title_not_empty", "char_length(trim(title)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc),
                            CreatorId = new Guid("655a37fa-b9e1-4cad-a684-383ac587e906"),
                            Description = "This is a sample quiz.",
                            IsPublic = true,
                            LanguageCode = "en",
                            Title = "Sample Quiz",
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_quiz_attempts");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quiz_attempts_quiz_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_quiz_attempts_user_id");

                    b.ToTable("quiz_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_quiz_attempts_score_non_negative", "score >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc),
                            QuizId = new Guid("d1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Score = 50,
                            UserId = new Guid("655a37fa-b9e1-4cad-a684-383ac587e906")
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.QuizLanguage", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_quiz_languages");

                    b.ToTable("quiz_languages", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "en"
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.QuizTopic", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_quiz_topics");

                    b.ToTable("quiz_topics", null, t =>
                        {
                            t.HasCheckConstraint("ck_topics_display_name_not_empty", "char_length(trim(display_name)) > 0");

                            t.HasCheckConstraint("ck_topics_name_not_empty", "char_length(trim(name)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Name = "geography",
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc),
                            DisplayName = "Geography",
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.RefreshToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenHash")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_token_hash_not_empty", "char_length(trim(token_hash)) > 0");
                        });
                });

            modelBuilder.Entity("Quizate.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("normalized_username")
                        .HasComputedColumnSql("lower(username)", true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_username");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_password_hash_not_empty", "char_length(trim(password_hash)) > 0");

                            t.HasCheckConstraint("ck_users_username_format", "username ~ '^[A-Za-z0-9_]+$'");

                            t.HasCheckConstraint("ck_users_username_not_empty", "char_length(trim(username)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("655a37fa-b9e1-4cad-a684-383ac587e906"),
                            CreatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc),
                            Email = "demo_user@example.com",
                            IsDeleted = false,
                            PasswordHash = "hashed_password_placeholder",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 17, 31, 60, DateTimeKind.Utc),
                            Username = "demo_user"
                        });
                });

            modelBuilder.Entity("QuizQuizTopic", b =>
                {
                    b.HasOne("Quizate.Data.Models.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_quiz_topic_quizzes_quizzes_id");

                    b.HasOne("Quizate.Data.Models.QuizTopic", null)
                        .WithMany()
                        .HasForeignKey("TopicsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_quiz_topic_quiz_topics_topics_name");
                });

            modelBuilder.Entity("Quizate.Data.Models.Question", b =>
                {
                    b.HasOne("Quizate.Data.Models.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_question_types_question_type_name");

                    b.HasOne("Quizate.Data.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_quizzes_quiz_id");

                    b.Navigation("QuestionType");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quizate.Data.Models.Quiz", b =>
                {
                    b.HasOne("Quizate.Data.Models.User", "Creator")
                        .WithMany("Quizzes")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("fk_quizzes_users_creator_id");

                    b.HasOne("Quizate.Data.Models.QuizLanguage", "Language")
                        .WithMany("Quizzes")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quizzes_quiz_languages_language_code");

                    b.Navigation("Creator");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Quizate.Data.Models.QuizAttempt", b =>
                {
                    b.HasOne("Quizate.Data.Models.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_attempts_quizzes_quiz_id");

                    b.HasOne("Quizate.Data.Models.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_quiz_attempts_users_user_id");

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quizate.Data.Models.RefreshToken", b =>
                {
                    b.HasOne("Quizate.Data.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quizate.Data.Models.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quizate.Data.Models.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quizate.Data.Models.QuizLanguage", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("Quizate.Data.Models.User", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("Quizzes");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
