/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersMeRouteImport } from './routes/users/me'
import { Route as QuizzesCreateRouteImport } from './routes/quizzes/create'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as QuizzesQuizIdRouteRouteImport } from './routes/quizzes/$quizId/route'
import { Route as QuizzesQuizIdIndexRouteImport } from './routes/quizzes/$quizId/index'
import { Route as QuizzesQuizIdTakeRouteImport } from './routes/quizzes/$quizId/take'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersMeRoute = UsersMeRouteImport.update({
  id: '/users/me',
  path: '/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesCreateRoute = QuizzesCreateRouteImport.update({
  id: '/quizzes/create',
  path: '/quizzes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const QuizzesQuizIdRouteRoute = QuizzesQuizIdRouteRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdIndexRoute = QuizzesQuizIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizzesQuizIdRouteRoute,
} as any)
const QuizzesQuizIdTakeRoute = QuizzesQuizIdTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => QuizzesQuizIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/users/me': typeof UsersMeRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
  '/quizzes/$quizId/': typeof QuizzesQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/users/me': typeof UsersMeRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/quizzes/$quizId': typeof QuizzesQuizIdRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/users/me': typeof UsersMeRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
  '/quizzes/$quizId/': typeof QuizzesQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quizzes/$quizId'
    | '/login'
    | '/register'
    | '/quizzes/create'
    | '/users/me'
    | '/quizzes/$quizId/take'
    | '/quizzes/$quizId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/quizzes/create'
    | '/users/me'
    | '/quizzes/$quizId/take'
    | '/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/quizzes/$quizId'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/quizzes/create'
    | '/users/me'
    | '/quizzes/$quizId/take'
    | '/quizzes/$quizId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  QuizzesQuizIdRouteRoute: typeof QuizzesQuizIdRouteRouteWithChildren
  QuizzesCreateRoute: typeof QuizzesCreateRoute
  UsersMeRoute: typeof UsersMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/me': {
      id: '/users/me'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof UsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/create': {
      id: '/quizzes/create'
      path: '/quizzes/create'
      fullPath: '/quizzes/create'
      preLoaderRoute: typeof QuizzesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId/': {
      id: '/quizzes/$quizId/'
      path: '/'
      fullPath: '/quizzes/$quizId/'
      preLoaderRoute: typeof QuizzesQuizIdIndexRouteImport
      parentRoute: typeof QuizzesQuizIdRouteRoute
    }
    '/quizzes/$quizId/take': {
      id: '/quizzes/$quizId/take'
      path: '/take'
      fullPath: '/quizzes/$quizId/take'
      preLoaderRoute: typeof QuizzesQuizIdTakeRouteImport
      parentRoute: typeof QuizzesQuizIdRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface QuizzesQuizIdRouteRouteChildren {
  QuizzesQuizIdTakeRoute: typeof QuizzesQuizIdTakeRoute
  QuizzesQuizIdIndexRoute: typeof QuizzesQuizIdIndexRoute
}

const QuizzesQuizIdRouteRouteChildren: QuizzesQuizIdRouteRouteChildren = {
  QuizzesQuizIdTakeRoute: QuizzesQuizIdTakeRoute,
  QuizzesQuizIdIndexRoute: QuizzesQuizIdIndexRoute,
}

const QuizzesQuizIdRouteRouteWithChildren =
  QuizzesQuizIdRouteRoute._addFileChildren(QuizzesQuizIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  QuizzesQuizIdRouteRoute: QuizzesQuizIdRouteRouteWithChildren,
  QuizzesCreateRoute: QuizzesCreateRoute,
  UsersMeRoute: UsersMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
